//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parolando.Properties {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Parolando.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una risorsa localizzata di tipo System.Drawing.Icon simile a (Icona).
        /// </summary>
        internal static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;words&gt;
        ///	&lt;word&gt;a&lt;/word&gt;
        ///	&lt;word&gt;abate&lt;/word&gt;
        ///	&lt;word&gt;abati&lt;/word&gt;
        ///	&lt;word&gt;abbagli&lt;/word&gt;
        ///	&lt;word&gt;abbaglia&lt;/word&gt;
        ///	&lt;word&gt;abbagliai&lt;/word&gt;
        ///	&lt;word&gt;abbagliamo&lt;/word&gt;
        ///	&lt;word&gt;abbagliano&lt;/word&gt;
        ///	&lt;word&gt;abbagliare&lt;/word&gt;
        ///	&lt;word&gt;abbagliata&lt;/word&gt;
        ///	&lt;word&gt;abbagliate&lt;/word&gt;
        ///	&lt;word&gt;abbagliati&lt;/word&gt;
        ///	&lt;word&gt;abbagliato&lt;/word&gt;
        ///	&lt;word&gt;abbagliava&lt;/word&gt;
        ///	&lt;word&gt;abbagliavi&lt;/word&gt;
        ///	&lt;word&gt;abbagliavo&lt;/word&gt;
        ///	&lt;word&gt;abbagliera&lt;/word&gt;
        ///	&lt;word&gt;abbagliero&lt;/word&gt;
        ///	&lt;word&gt;abbaglino&lt;/word&gt;
        ///	&lt;word&gt;abbaglio&lt;/word&gt;
        ///	&lt;word&gt;abb [stringa troncata]&quot;;.
        /// </summary>
        internal static string italian {
            get {
                return ResourceManager.GetString("italian", resourceCulture);
            }
        }
    }
}
